from pathlib import Path

WIN_NAME = "Classroom Monitor"
WINDOW_NAME = WIN_NAME

BASE_DIR = Path(__file__).resolve().parent
PROJECT_DIR = BASE_DIR.parent

YOLO_CONF = 0.35
YOLO_FACE_CONF = 0.35
YOLO_HEAD_CONF = 0.30
YOLO_SIDEFACE_CONF = 0.32
YOLO_MODEL_PATH = str(PROJECT_DIR / "runs" / "detect" / "classroom_detector" / "weights" / "best.pt")

MIN_SAMPLES_FOR_REPORT = 15
MIN_VISIBLE_RATIO_FOR_REPORT = 0.15
MIN_SPAN_SECONDS_FOR_REPORT = 8.0

CAMERA_INDEX = 1
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
FPS = 60
USE_LETTERBOX_VIEW = True

MAX_STUDENTS = 25

TRACK_TTL_S = 3.0
IOU_MATCH_T = 0.25
CENTER_DIST_T = 140
MIN_TRACK_POINTS = 15

DETECT_EVERY_N_FRAMES = 3
HEAD_DETECT_EVERY_N_FRAMES = 4

DETECT_WIDTH = 1440
CROP_SIZE = 256

ENABLE_FACE_DETECTION = True
REFINE_LANDMARKS = True
MIN_DET_CONF = 0.28
MIN_TRK_CONF = 0.5

FACE_BOX_MIN_AREA = 700
FACE_BOX_MIN_SIZE = 16
FACE_BOX_MAX_W_RATIO = 0.72
FACE_BOX_MAX_H_RATIO = 0.92
FACE_BOX_MIN_ASPECT = 0.30
FACE_BOX_MAX_ASPECT = 1.90
FACE_MESH_EXPAND_SCALE = 1.18
FACE_INSIDE_HEAD_MIN_IOU = 0.03
FACE_CENTER_MIN_Y_RATIO = 0.08
FACE_CENTER_MAX_Y_RATIO = 0.92
FACE_MESH_MIN_W = 24
FACE_MESH_MIN_H = 24

HEAD_BOX_MIN_AREA = 700
HEAD_BOX_MIN_SIZE = 24
HEAD_BOX_MAX_W_RATIO = 0.82
HEAD_BOX_MAX_H_RATIO = 0.96
HEAD_BOX_MIN_ASPECT = 0.35
HEAD_BOX_MAX_ASPECT = 1.95

HEAD_MIN_CENTER_Y_RATIO = 0.18
HEAD_MAX_CENTER_Y_RATIO = 0.96
HEAD_MIN_AREA_RATIO = 0.0012
HEAD_MAX_AREA_RATIO = 0.18
HEAD_EDGE_MARGIN_RATIO = 0.01
HEAD_REJECT_IF_TOO_BRIGHT = True
HEAD_BRIGHT_MEAN_THRESH = 245.0
HEAD_BRIGHT_STD_THRESH = 12.0

INFER_HEAD_FROM_FACE_W_SCALE = 1.55
INFER_HEAD_FROM_FACE_H_SCALE = 1.95

COUNT_HEADS_WHEN_NO_FACE = True

EYES_CLOSED_EAR_T = 0.22
DROWSY_CLOSED_MS = 900
PERCLOS_WINDOW_S = 60

EAR_BLINK_THRESHOLD = 0.20
EAR_BLINK_CONSEC_FRAMES = 3
EAR_WINDOW_SECONDS = 10.0
BLINK_WINDOW_SECONDS = 60.0

METRIC_READY_MIN_FRAMES = 20
SCORE_UPDATE_INTERVAL = 2.0
AVERAGE_ACTIVE_WINDOW = 10.0

EAR_WEIGHT = 0.6
BLINK_WEIGHT = 0.4

LOOK_MIN = 0.35
LOOK_MAX = 0.65
ATTENTION_WINDOW_SECONDS = 10.0

ALERT_CLASS_AVG_PCT = 60
ALERT_HOLD_S = 8
ALERT_FATIGUE_PCT = 50
ALERT_ATTENTION_MIN_PCT = 50

ALERT_CLASS_FATIGUE_ON = 50
ALERT_CLASS_FATIGUE_OFF = 45
ALERT_CLASS_ATTENTION_ON = 50
ALERT_CLASS_ATTENTION_OFF = 55

ALERT_STUDENT_FATIGUE_ON = 60
ALERT_STUDENT_FATIGUE_OFF = 52
ALERT_STUDENT_ATTENTION_ON = 50
ALERT_STUDENT_ATTENTION_OFF = 55

ALERT_STUDENT_FATIGUE_CRITICAL = 70
ALERT_STUDENT_ATTENTION_CRITICAL = 30

ALERT_CLASS_HOLD_S = 6.0
ALERT_STUDENT_HOLD_S = 4.0

MIN_ACTIVE_STUDENTS_FOR_CLASS_ALERT = 1

SHOW_FACE_BOX = True
SHOW_DEBUG_TEXT = False
LOGGING_ENABLED = False

DB_PATH = "classroom_data.db"
REPORT_INTERVAL_S = 60
RECENT_REPORTS_IN_UI = 3
SESSION_REPORTS_DIR = "reports"

FACE_ID_SIM_THRESHOLD = 0.75
FACE_ID_MIN_FACE_SIZE = 60
FACE_ID_MIN_BLUR_SCORE = 50.0
FACE_ID_CANDIDATE_HITS = 6
FACE_ID_CANDIDATE_TTL_S = 3.0
FACE_ID_EVERY_N_FRAMES = 6

ENABLE_PERIODIC_REFRESH = True
REFRESH_EVERY_N_FRAMES = 240
REFRESH_GRACE_FRAMES = 15
REFRESH_CACHE_TTL_S = 2.0

REFRESH_REID_IOU_T = 0.18
REFRESH_REID_CENTER_DIST_T = 110
REFRESH_REID_FACE_SIM_T = 0.74
REFRESH_REID_REQUIRE_CLASS_MATCH = True

ENABLE_SOUND_ALERT = True
ALERT_SOUND_FILE = None
ALERT_BEEP_FREQ = 880
ALERT_BEEP_DURATION_MS = 180
ALERT_SOUND_COOLDOWN_S = 8.0
SOUND_ALERT_MIN_INTERVAL_S = 8.0

ENABLE_INDIVIDUAL_ALERTS = True
MAX_STUDENT_ALERTS_IN_UI = 5

ATTENTION_THRESHOLDS = {
    "crit": (0, 30),
    "low": (31, 49),
    "ok": (50, 69),
    "good": (70, 89),
    "ideal": (90, 100),
}

FATIGUE_THRESHOLDS = {
    "ideal": (0, 10),
    "good": (11, 30),
    "ok": (31, 50),
    "low": (51, 89),
    "crit": (90, 100),
}

DECISION_PRIORITY = {
    "critical": 0,
    "warning": 1,
    "fatigue_risk": 2,
    "refocus": 2,
    "monitor": 3,
    "stable": 4,
}

DECISION_COLORS = {
    "critical": "#d32f2f",
    "warning": "#f57c00",
    "fatigue_risk": "#fbc02d",
    "refocus": "#ffa000",
    "monitor": "#1976d2",
    "stable": "#388e3c",
}

GAZE_MAJORITY_HISTORY_FRAMES = 30
ATTENTION_MAJORITY_WEIGHT = 0.70

ENABLE_ATTENTION_ML = True
ATTENTION_MODEL_PATH = "models/attention_model.keras"
ATTENTION_CLASS_NAMES_PATH = "models/attention_class_names.json"
ATTENTION_ML_WEIGHT = 0.30
ATTENTION_ML_MIN_CONF = 0.60

SESSION_CALIBRATION_SECONDS = 6

ENABLE_SEAT_MEMORY = True
SEAT_MEMORY_DURATION_S = 1.5 * 60 * 60
SEAT_MAX_MISSING_S = 180.0
SEAT_MAX_DIST_PX = 200.0
MIN_OBSERVATIONS_FOR_UNIQUE_ID = 10
LIVE_QUALITY_MIN_SAMPLES = 20

ATTENTION_LOW_CONFIRM_SECONDS = 120.0
ATTENTION_LOW_THRESHOLD = 50
ATTENTION_RECOVERY_THRESHOLD = 60
ATTENTION_SHORT_DROP_VALUE = 85