WIN_NAME = "Classroom Monitor"
WINDOW_NAME = WIN_NAME

# Camera / stream
CAMERA_INDEX = 1
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
FPS = 30
USE_LETTERBOX_VIEW = True

# General capacity
MAX_STUDENTS = 25

# Tracking
TRACK_TTL_S = 3.0
IOU_MATCH_T = 0.25
CENTER_DIST_T = 140
MIN_TRACK_POINTS = 15

# Detection cadence
DETECT_EVERY_N_FRAMES = 3
HEAD_DETECT_EVERY_N_FRAMES = 5

# Detection sizing
DETECT_WIDTH = 1440
CROP_SIZE = 256

# Face detection
ENABLE_FACE_DETECTION = True
REFINE_LANDMARKS = True
MIN_DET_CONF = 0.28
MIN_TRK_CONF = 0.5

# Face box validation
FACE_BOX_MIN_SIZE = 16
FACE_BOX_MAX_W_RATIO = 0.72
FACE_BOX_MAX_H_RATIO = 0.92
FACE_BOX_MIN_ASPECT = 0.30
FACE_BOX_MAX_ASPECT = 1.90
FACE_MESH_EXPAND_SCALE = 1.18
FACE_INSIDE_HEAD_MIN_IOU = 0.03

# Head box validation
HEAD_BOX_MIN_SIZE = 24
HEAD_BOX_MAX_W_RATIO = 0.82
HEAD_BOX_MAX_H_RATIO = 0.96
HEAD_BOX_MIN_ASPECT = 0.35
HEAD_BOX_MAX_ASPECT = 1.95

# Head anti-false-positive filters
HEAD_MIN_CENTER_Y_RATIO = 0.18
HEAD_MAX_CENTER_Y_RATIO = 0.96
HEAD_MIN_AREA_RATIO = 0.0012
HEAD_MAX_AREA_RATIO = 0.18
HEAD_EDGE_MARGIN_RATIO = 0.01
HEAD_REJECT_IF_TOO_BRIGHT = True
HEAD_BRIGHT_MEAN_THRESH = 245.0
HEAD_BRIGHT_STD_THRESH = 12.0

# Count behavior
COUNT_HEADS_WHEN_NO_FACE = True

# Fatigue
EYES_CLOSED_EAR_T = 0.22
DROWSY_CLOSED_MS = 900
PERCLOS_WINDOW_S = 60

EAR_BLINK_THRESHOLD = 0.20
EAR_BLINK_CONSEC_FRAMES = 3
EAR_WINDOW_SECONDS = 10.0
BLINK_WINDOW_SECONDS = 60.0

METRIC_READY_MIN_FRAMES = 20
SCORE_UPDATE_INTERVAL = 2.0
AVERAGE_ACTIVE_WINDOW = 10.0

EAR_WEIGHT = 0.6
BLINK_WEIGHT = 0.4

# Attention
LOOK_MIN = 0.35
LOOK_MAX = 0.65
ATTENTION_WINDOW_SECONDS = 10.0

# Alerts
ALERT_CLASS_AVG_PCT = 60
ALERT_HOLD_S = 8

# UI / logging
SHOW_FACE_BOX = True
SHOW_DEBUG_TEXT = False
LOGGING_ENABLED = False

# Storage / reports
DB_PATH = "classroom_monitor.db"
REPORT_INTERVAL_S = 60
RECENT_REPORTS_IN_UI = 3
SESSION_REPORTS_DIR = "reports"

# Identity
FACE_ID_SIM_THRESHOLD = 0.75
FACE_ID_MIN_FACE_SIZE = 60
FACE_ID_MIN_BLUR_SCORE = 50.0
FACE_ID_CANDIDATE_HITS = 6
FACE_ID_CANDIDATE_TTL_S = 3.0
FACE_ID_EVERY_N_FRAMES = 6